### PR TITLE
Describe types

### PR DESCRIPTION
**Pull request by MasseGuillaume**

### CODE REVIEW

**Comment by heathermiller** [comment]
For the record, yesterday in our group meeting, we all agreed that this would be best if you spent 1-2 days turning this into package and putting it on the VSCode marketplace.

**Comment by MasseGuillaume** [comment]
@heathermiller I'm just finishing up the task I was working on before to jump to the next one.

**Comment by heathermiller** [comment]
Right. And the next one that we agreed that you would do is getting it on the VSCode marketplace.

**Comment by MasseGuillaume** [comment]
:+1: Roger that.

**Comment by heathermiller** [comment]
👍 Merci!

**Comment by MasseGuillaume** [comment]
@heathermiller

> For the record, yesterday in our group meeting, we all agreed that this would be best if you spent 1-2 days turning this into package and putting it on the VSCode marketplace.

For the record, we never agreed on a 1-2 days timeframe. I think it will take from 3 to 4 days.

**Comment by heathermiller** [comment]
@MasseGuillaume Other engineers in the group meeting estimated 1 day (e.g., @olafurpg). You corrected everyone and said 2. @sjrd and the rest of the group witnessed it.

**Comment by MasseGuillaume** [comment]
@heathermiller I just hit a roadblock: it's not possible to run the text-to-speech module I use on the browser inside of vscode. The `AudioContext` api is not available inside of vscode.

I propose the following workaround: use a client/server. The extension (client) spawn a java server. It communicates via stdin/stdout and text messages when accessible-scala commands are triggered. The drawback of this approach compared to the all-javascript solution is the distribution. The speech module is a native binary with a jni api. This means that each platform (windows / mac / linux*) needs this binary.

**EDIT**
@olafurpg proposed to use shim from npm that would enable text-to-speech (TTS) on the vscode environment. I spent some time to identify candidates, here is what I found:

* native module (for example: [node-espeak](https://github.com/Prior99/node-espeak)). It's not possible to run native modules on vscode: [#658](https://github.com/Microsoft/vscode/issues/658)

* process spawning (for example: [say.js](https://github.com/Marak/say.js/blob/master/platform/linux.js)) 
   * requires a TTS program to be installed
   * canceling speach requires killing a process (latency and sound quality are issues)

**Comment by heathermiller** [comment]
I would advise against a client/server approach. It's a rather complicated way to do it, and the last thing we want for a blind developer is their IDE working on and off.

I've looked around online and it seems another approach could be to use some built-in os-provided facility for text-to-speech. We could just detect the user's operating system and choose whichever facility they should have. There is even a plug-in on the VSCode marketplace for reading code for OSX users.

**Comment by MasseGuillaume** [comment]
@heathermiller if this is the plugin you have in mind: https://github.com/mattbierner/vscode-speech/blob/master/src/extension.ts#L3

It's using say.js and suffers from the disadvantages of the process spawning technique.

The client/server approach is used in [emacspeak](https://github.com/tvraman/emacspeak/blob/master/servers/linux-espeak/tclespeak.cpp) and it's also the technique I used in the sublime-text plugin I built for testing purposes some time ago: https://github.com/scalacenter/accessible-scala/tree/master/plugins/sublime-text.

I'm currently stubbing out the TTS part until we find a solution. I will continue to work on other tasks related to the vscode plugin: selection ranges, keyboard shortcuts, etc.

**Comment by heathermiller** [comment]
> It's using say.js and suffers from the disadvantages of the process spawning technique.

I don't think that the classification of requiring text-to-speech software is a disadvantage. Rather, as I suggested in my last comment, I think it's an advantage because it means no complicated client/server architecture, and it's either already-installed or it's a one-line install.

Many platforms already even come with pre-installed text-to-speech software. OSX and Ubuntu have `say`. And on Windows, you can use `System.Speech` from PowerShell without installing anything.

It really seems like it would be a lot simpler to detect the OS the user is using and to either use `say` if the user is running OSX or Linux, and PowerShell `System.Speech` if the user is using Windows.

**Comment by MasseGuillaume** [comment]
@heathermiller 

Ok, I will implement the process spawning technique since it's not really complicated / does not take too much time. If I remember well, when I tried this with the sublime-text 1) it was too slow (spawning/killing the process) 2) the sound glitches when the process is killed. I will let you try, maybe I'm wrong here.

**Comment by heathermiller** [comment]
:+1: Sounds good!

As an aside, I think some small amount of glitchiness in the sound can be tolerated. I think the main thing is that the way we speak the code makes the most logical sense to the end-user. So we should focus on that the most.

**Pull request closed without merging**
